apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysqldb
  name: mysqldb
  namespace: aula-kubernetes
spec:
  selector:
    matchLabels:
      app: mysqldb
  serviceName: mysqldb
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_TCP_PORT
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: MYSQL_TCP_PORT
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: TZ
          image: mysql:8.0
          name: mysqldb
          ports: 
            - containerPort: 3306
      
          

          